version: '3'

services:
  scraper:
    build: ./scraper
    tty: true
    depends_on:
      - postgres

  postgres:
    hostname: postgres
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: pep
      POSTGRES_PASSWORD: pep
      POSTGRES_DB: pepscrape
    # volumes:
    #   - db_data:/var/lib/postgresql/data
